# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: navirice_image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='navirice_image.proto',
  package='navirice',
  syntax='proto3',
  serialized_pb=_b('\n\x14navirice_image.proto\x12\x08navirice\"\xb2\x01\n\nProtoImage\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x10\n\x08\x63hannels\x18\x03 \x01(\r\x12\x30\n\tdata_type\x18\x04 \x01(\x0e\x32\x1d.navirice.ProtoImage.DataType\x12\x11\n\tdata_size\x18\x05 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\" \n\x08\x44\x61taType\x12\t\n\x05\x46LOAT\x10\x00\x12\t\n\x05UBYTE\x10\x01\"\x88\x01\n\rProtoImageSet\x12\r\n\x05\x63ount\x18\x01 \x01(\x04\x12!\n\x03RGB\x18\x02 \x01(\x0b\x32\x14.navirice.ProtoImage\x12#\n\x05\x44\x65pth\x18\x03 \x01(\x0b\x32\x14.navirice.ProtoImage\x12 \n\x02IR\x18\x04 \x01(\x0b\x32\x14.navirice.ProtoImageb\x06proto3')
)



_PROTOIMAGE_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='navirice.ProtoImage.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UBYTE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=181,
  serialized_end=213,
)
_sym_db.RegisterEnumDescriptor(_PROTOIMAGE_DATATYPE)


_PROTOIMAGE = _descriptor.Descriptor(
  name='ProtoImage',
  full_name='navirice.ProtoImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='navirice.ProtoImage.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='navirice.ProtoImage.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='navirice.ProtoImage.channels', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='navirice.ProtoImage.data_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_size', full_name='navirice.ProtoImage.data_size', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='navirice.ProtoImage.data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROTOIMAGE_DATATYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=213,
)


_PROTOIMAGESET = _descriptor.Descriptor(
  name='ProtoImageSet',
  full_name='navirice.ProtoImageSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='navirice.ProtoImageSet.count', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RGB', full_name='navirice.ProtoImageSet.RGB', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Depth', full_name='navirice.ProtoImageSet.Depth', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IR', full_name='navirice.ProtoImageSet.IR', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=352,
)

_PROTOIMAGE.fields_by_name['data_type'].enum_type = _PROTOIMAGE_DATATYPE
_PROTOIMAGE_DATATYPE.containing_type = _PROTOIMAGE
_PROTOIMAGESET.fields_by_name['RGB'].message_type = _PROTOIMAGE
_PROTOIMAGESET.fields_by_name['Depth'].message_type = _PROTOIMAGE
_PROTOIMAGESET.fields_by_name['IR'].message_type = _PROTOIMAGE
DESCRIPTOR.message_types_by_name['ProtoImage'] = _PROTOIMAGE
DESCRIPTOR.message_types_by_name['ProtoImageSet'] = _PROTOIMAGESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoImage = _reflection.GeneratedProtocolMessageType('ProtoImage', (_message.Message,), dict(
  DESCRIPTOR = _PROTOIMAGE,
  __module__ = 'navirice_image_pb2'
  # @@protoc_insertion_point(class_scope:navirice.ProtoImage)
  ))
_sym_db.RegisterMessage(ProtoImage)

ProtoImageSet = _reflection.GeneratedProtocolMessageType('ProtoImageSet', (_message.Message,), dict(
  DESCRIPTOR = _PROTOIMAGESET,
  __module__ = 'navirice_image_pb2'
  # @@protoc_insertion_point(class_scope:navirice.ProtoImageSet)
  ))
_sym_db.RegisterMessage(ProtoImageSet)


# @@protoc_insertion_point(module_scope)
