// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: navirice_image.proto

#include "navirice_image.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace navirice {
class ProtoImageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtoImage>
      _instance;
} _ProtoImage_default_instance_;
class ProtoImageSetDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtoImageSet>
      _instance;
} _ProtoImageSet_default_instance_;
}  // namespace navirice
namespace protobuf_navirice_5fimage_2eproto {
void InitDefaultsProtoImageImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::navirice::_ProtoImage_default_instance_;
    new (ptr) ::navirice::ProtoImage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::navirice::ProtoImage::InitAsDefaultInstance();
}

void InitDefaultsProtoImage() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsProtoImageImpl);
}

void InitDefaultsProtoImageSetImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_navirice_5fimage_2eproto::InitDefaultsProtoImage();
  {
    void* ptr = &::navirice::_ProtoImageSet_default_instance_;
    new (ptr) ::navirice::ProtoImageSet();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::navirice::ProtoImageSet::InitAsDefaultInstance();
}

void InitDefaultsProtoImageSet() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsProtoImageSetImpl);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImage, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImage, height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImage, channels_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImage, data_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImage, data_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImage, data_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImageSet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImageSet, count_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImageSet, rgb_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImageSet, depth_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::navirice::ProtoImageSet, ir_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::navirice::ProtoImage)},
  { 11, -1, sizeof(::navirice::ProtoImageSet)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::navirice::_ProtoImage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::navirice::_ProtoImageSet_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "navirice_image.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024navirice_image.proto\022\010navirice\"\262\001\n\nPro"
      "toImage\022\r\n\005width\030\001 \001(\r\022\016\n\006height\030\002 \001(\r\022\020"
      "\n\010channels\030\003 \001(\r\0220\n\tdata_type\030\004 \001(\0162\035.na"
      "virice.ProtoImage.DataType\022\021\n\tdata_size\030"
      "\005 \001(\r\022\014\n\004data\030\006 \001(\014\" \n\010DataType\022\t\n\005FLOAT"
      "\020\000\022\t\n\005UBYTE\020\001\"\210\001\n\rProtoImageSet\022\r\n\005count"
      "\030\001 \001(\004\022!\n\003RGB\030\002 \001(\0132\024.navirice.ProtoImag"
      "e\022#\n\005Depth\030\003 \001(\0132\024.navirice.ProtoImage\022 "
      "\n\002IR\030\004 \001(\0132\024.navirice.ProtoImageb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 360);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "navirice_image.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_navirice_5fimage_2eproto
namespace navirice {
const ::google::protobuf::EnumDescriptor* ProtoImage_DataType_descriptor() {
  protobuf_navirice_5fimage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_navirice_5fimage_2eproto::file_level_enum_descriptors[0];
}
bool ProtoImage_DataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ProtoImage_DataType ProtoImage::FLOAT;
const ProtoImage_DataType ProtoImage::UBYTE;
const ProtoImage_DataType ProtoImage::DataType_MIN;
const ProtoImage_DataType ProtoImage::DataType_MAX;
const int ProtoImage::DataType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void ProtoImage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtoImage::kWidthFieldNumber;
const int ProtoImage::kHeightFieldNumber;
const int ProtoImage::kChannelsFieldNumber;
const int ProtoImage::kDataTypeFieldNumber;
const int ProtoImage::kDataSizeFieldNumber;
const int ProtoImage::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtoImage::ProtoImage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_navirice_5fimage_2eproto::InitDefaultsProtoImage();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:navirice.ProtoImage)
}
ProtoImage::ProtoImage(const ProtoImage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.data().size() > 0) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  ::memcpy(&width_, &from.width_,
    static_cast<size_t>(reinterpret_cast<char*>(&data_size_) -
    reinterpret_cast<char*>(&width_)) + sizeof(data_size_));
  // @@protoc_insertion_point(copy_constructor:navirice.ProtoImage)
}

void ProtoImage::SharedCtor() {
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&data_size_) -
      reinterpret_cast<char*>(&width_)) + sizeof(data_size_));
  _cached_size_ = 0;
}

ProtoImage::~ProtoImage() {
  // @@protoc_insertion_point(destructor:navirice.ProtoImage)
  SharedDtor();
}

void ProtoImage::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ProtoImage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProtoImage::descriptor() {
  ::protobuf_navirice_5fimage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_navirice_5fimage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ProtoImage& ProtoImage::default_instance() {
  ::protobuf_navirice_5fimage_2eproto::InitDefaultsProtoImage();
  return *internal_default_instance();
}

ProtoImage* ProtoImage::New(::google::protobuf::Arena* arena) const {
  ProtoImage* n = new ProtoImage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ProtoImage::Clear() {
// @@protoc_insertion_point(message_clear_start:navirice.ProtoImage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&data_size_) -
      reinterpret_cast<char*>(&width_)) + sizeof(data_size_));
  _internal_metadata_.Clear();
}

bool ProtoImage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:navirice.ProtoImage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 width = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 height = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 channels = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &channels_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .navirice.ProtoImage.DataType data_type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_data_type(static_cast< ::navirice::ProtoImage_DataType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 data_size = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &data_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes data = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:navirice.ProtoImage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:navirice.ProtoImage)
  return false;
#undef DO_
}

void ProtoImage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:navirice.ProtoImage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 width = 1;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->width(), output);
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->height(), output);
  }

  // uint32 channels = 3;
  if (this->channels() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->channels(), output);
  }

  // .navirice.ProtoImage.DataType data_type = 4;
  if (this->data_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->data_type(), output);
  }

  // uint32 data_size = 5;
  if (this->data_size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->data_size(), output);
  }

  // bytes data = 6;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      6, this->data(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:navirice.ProtoImage)
}

::google::protobuf::uint8* ProtoImage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:navirice.ProtoImage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 width = 1;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->width(), target);
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->height(), target);
  }

  // uint32 channels = 3;
  if (this->channels() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->channels(), target);
  }

  // .navirice.ProtoImage.DataType data_type = 4;
  if (this->data_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->data_type(), target);
  }

  // uint32 data_size = 5;
  if (this->data_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->data_size(), target);
  }

  // bytes data = 6;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        6, this->data(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:navirice.ProtoImage)
  return target;
}

size_t ProtoImage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:navirice.ProtoImage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes data = 6;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  // uint32 width = 1;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width());
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->height());
  }

  // uint32 channels = 3;
  if (this->channels() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->channels());
  }

  // .navirice.ProtoImage.DataType data_type = 4;
  if (this->data_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->data_type());
  }

  // uint32 data_size = 5;
  if (this->data_size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->data_size());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProtoImage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:navirice.ProtoImage)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoImage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ProtoImage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:navirice.ProtoImage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:navirice.ProtoImage)
    MergeFrom(*source);
  }
}

void ProtoImage::MergeFrom(const ProtoImage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:navirice.ProtoImage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.channels() != 0) {
    set_channels(from.channels());
  }
  if (from.data_type() != 0) {
    set_data_type(from.data_type());
  }
  if (from.data_size() != 0) {
    set_data_size(from.data_size());
  }
}

void ProtoImage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:navirice.ProtoImage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoImage::CopyFrom(const ProtoImage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:navirice.ProtoImage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoImage::IsInitialized() const {
  return true;
}

void ProtoImage::Swap(ProtoImage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtoImage::InternalSwap(ProtoImage* other) {
  using std::swap;
  data_.Swap(&other->data_);
  swap(width_, other->width_);
  swap(height_, other->height_);
  swap(channels_, other->channels_);
  swap(data_type_, other->data_type_);
  swap(data_size_, other->data_size_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ProtoImage::GetMetadata() const {
  protobuf_navirice_5fimage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_navirice_5fimage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ProtoImageSet::InitAsDefaultInstance() {
  ::navirice::_ProtoImageSet_default_instance_._instance.get_mutable()->rgb_ = const_cast< ::navirice::ProtoImage*>(
      ::navirice::ProtoImage::internal_default_instance());
  ::navirice::_ProtoImageSet_default_instance_._instance.get_mutable()->depth_ = const_cast< ::navirice::ProtoImage*>(
      ::navirice::ProtoImage::internal_default_instance());
  ::navirice::_ProtoImageSet_default_instance_._instance.get_mutable()->ir_ = const_cast< ::navirice::ProtoImage*>(
      ::navirice::ProtoImage::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtoImageSet::kCountFieldNumber;
const int ProtoImageSet::kRGBFieldNumber;
const int ProtoImageSet::kDepthFieldNumber;
const int ProtoImageSet::kIRFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtoImageSet::ProtoImageSet()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_navirice_5fimage_2eproto::InitDefaultsProtoImageSet();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:navirice.ProtoImageSet)
}
ProtoImageSet::ProtoImageSet(const ProtoImageSet& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_rgb()) {
    rgb_ = new ::navirice::ProtoImage(*from.rgb_);
  } else {
    rgb_ = NULL;
  }
  if (from.has_depth()) {
    depth_ = new ::navirice::ProtoImage(*from.depth_);
  } else {
    depth_ = NULL;
  }
  if (from.has_ir()) {
    ir_ = new ::navirice::ProtoImage(*from.ir_);
  } else {
    ir_ = NULL;
  }
  count_ = from.count_;
  // @@protoc_insertion_point(copy_constructor:navirice.ProtoImageSet)
}

void ProtoImageSet::SharedCtor() {
  ::memset(&rgb_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&count_) -
      reinterpret_cast<char*>(&rgb_)) + sizeof(count_));
  _cached_size_ = 0;
}

ProtoImageSet::~ProtoImageSet() {
  // @@protoc_insertion_point(destructor:navirice.ProtoImageSet)
  SharedDtor();
}

void ProtoImageSet::SharedDtor() {
  if (this != internal_default_instance()) delete rgb_;
  if (this != internal_default_instance()) delete depth_;
  if (this != internal_default_instance()) delete ir_;
}

void ProtoImageSet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProtoImageSet::descriptor() {
  ::protobuf_navirice_5fimage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_navirice_5fimage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ProtoImageSet& ProtoImageSet::default_instance() {
  ::protobuf_navirice_5fimage_2eproto::InitDefaultsProtoImageSet();
  return *internal_default_instance();
}

ProtoImageSet* ProtoImageSet::New(::google::protobuf::Arena* arena) const {
  ProtoImageSet* n = new ProtoImageSet;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ProtoImageSet::Clear() {
// @@protoc_insertion_point(message_clear_start:navirice.ProtoImageSet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && rgb_ != NULL) {
    delete rgb_;
  }
  rgb_ = NULL;
  if (GetArenaNoVirtual() == NULL && depth_ != NULL) {
    delete depth_;
  }
  depth_ = NULL;
  if (GetArenaNoVirtual() == NULL && ir_ != NULL) {
    delete ir_;
  }
  ir_ = NULL;
  count_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool ProtoImageSet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:navirice.ProtoImageSet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 count = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .navirice.ProtoImage RGB = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_rgb()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .navirice.ProtoImage Depth = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_depth()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .navirice.ProtoImage IR = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_ir()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:navirice.ProtoImageSet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:navirice.ProtoImageSet)
  return false;
#undef DO_
}

void ProtoImageSet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:navirice.ProtoImageSet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 count = 1;
  if (this->count() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->count(), output);
  }

  // .navirice.ProtoImage RGB = 2;
  if (this->has_rgb()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->rgb_, output);
  }

  // .navirice.ProtoImage Depth = 3;
  if (this->has_depth()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->depth_, output);
  }

  // .navirice.ProtoImage IR = 4;
  if (this->has_ir()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->ir_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:navirice.ProtoImageSet)
}

::google::protobuf::uint8* ProtoImageSet::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:navirice.ProtoImageSet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 count = 1;
  if (this->count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->count(), target);
  }

  // .navirice.ProtoImage RGB = 2;
  if (this->has_rgb()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->rgb_, deterministic, target);
  }

  // .navirice.ProtoImage Depth = 3;
  if (this->has_depth()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, *this->depth_, deterministic, target);
  }

  // .navirice.ProtoImage IR = 4;
  if (this->has_ir()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, *this->ir_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:navirice.ProtoImageSet)
  return target;
}

size_t ProtoImageSet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:navirice.ProtoImageSet)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .navirice.ProtoImage RGB = 2;
  if (this->has_rgb()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->rgb_);
  }

  // .navirice.ProtoImage Depth = 3;
  if (this->has_depth()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->depth_);
  }

  // .navirice.ProtoImage IR = 4;
  if (this->has_ir()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->ir_);
  }

  // uint64 count = 1;
  if (this->count() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->count());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProtoImageSet::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:navirice.ProtoImageSet)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoImageSet* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ProtoImageSet>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:navirice.ProtoImageSet)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:navirice.ProtoImageSet)
    MergeFrom(*source);
  }
}

void ProtoImageSet::MergeFrom(const ProtoImageSet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:navirice.ProtoImageSet)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_rgb()) {
    mutable_rgb()->::navirice::ProtoImage::MergeFrom(from.rgb());
  }
  if (from.has_depth()) {
    mutable_depth()->::navirice::ProtoImage::MergeFrom(from.depth());
  }
  if (from.has_ir()) {
    mutable_ir()->::navirice::ProtoImage::MergeFrom(from.ir());
  }
  if (from.count() != 0) {
    set_count(from.count());
  }
}

void ProtoImageSet::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:navirice.ProtoImageSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoImageSet::CopyFrom(const ProtoImageSet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:navirice.ProtoImageSet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoImageSet::IsInitialized() const {
  return true;
}

void ProtoImageSet::Swap(ProtoImageSet* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtoImageSet::InternalSwap(ProtoImageSet* other) {
  using std::swap;
  swap(rgb_, other->rgb_);
  swap(depth_, other->depth_);
  swap(ir_, other->ir_);
  swap(count_, other->count_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ProtoImageSet::GetMetadata() const {
  protobuf_navirice_5fimage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_navirice_5fimage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace navirice

// @@protoc_insertion_point(global_scope)
